image: ruby:2.5.1

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rake test
